Proyecto
Eduardo Javier Hevia Calderón
# 999005037


Importar CSV
#1
```{r}
library(tidyverse)
library(gapminder)
library(dplyr)
library(ggplot2)

yearly <- read.csv(file = './deaths_handwashing.csv')
yearly
```
#2
```{r}

yearly <- yearly %>%
  mutate(proportion_deaths = round(deaths / births, 2) )


yearly

```
#3

```{r}
# gráfica lineal
yearly
ggplot(data = yearly, aes(x=year, y= proportion_deaths, color=clinic )) + 
  stat_smooth(se=FALSE)
```

#4
```{r}
#
monthly <- read_csv(file = "./deaths_clinic_1.csv")
monthly

monthly <- monthly %>%
  mutate(proportion_deaths = round(deaths / births, 2) )

monthly
head(monthly, 10) # primer 10 filas para mostrar
```
#5
```{r}
library(tidyverse)

monthly
ggplot(data = monthly, aes(x= date, y=proportion_deaths)) +
   geom_line(colour= "blue") +
    labs(y = "Proporcionar de muertos", 
         x = "Fecha", 
         title = "El efecto del lavado de manos", 
         caption = "Fuente: Elavoración propia")
```
#6
```{r}
library(dplyr)
library(tibble)
library(ggplot2)


monthly <- monthly %>%
  mutate(handwashing_started = ifelse( date >= '1847-01-01', TRUE, FALSE))

monthly

ggplot(monthly, aes(x=date, y=proportion_deaths, color=handwashing_started)) +
  geom_line()+
    labs(y = "Proporcionar de muertos", 
         x = "Años", 
         title = "Resultados del lavado de manos", 
         caption = "Fuente: Elavoración propia")

```
#7
```{r}
monthly

month_summary <- monthly %>%
  group_by(handwashing_started) %>%
  summarise(mean_proportion_deaths = median(proportion_deaths))

```


